### ISSUE TITLE
Thread.html Cross Origin Request Blocking

### ISSUE THREAD

**Issue by SalamanderSandwich** [murrty/YChanEx#1]
Chrome blocks cross origin requests, so Thread.html can't be viewed. Please save external requirements in a local folder or embed them into the file.
![image](https://user-images.githubusercontent.com/29418056/35826122-6b322a80-0a7d-11e8-861a-f27aff75e8aa.png)

**Comment by murrty** [comment]
What site are you trying to download from?

**Comment by SalamanderSandwich** [comment]
4chan.org/a

**Comment by murrty** [comment]
Since 4chan introduced off-site scripts it seems to have broken a lot of this, I have not run into this during testing on boards I do use.

Easiest fix, currently, is manually selecting this code (See image) and removing it which fixes it. It looks like other browsers have issue with CSS with it as well. I'll need to test some other boards to check to see if it's static.

![Image](https://user-images.githubusercontent.com/35756280/35953782-d9b062cc-0c4b-11e8-8db6-18339e10fc6b.png)

**Comment by murrty** [comment]
Fixed in v1.683 (more or less, specifically tested on /a/)
