### ISSUE TITLE
New release coming?

### ISSUE THREAD

**Issue by No0negit** [murrty/YChanEx#12]
Hello, any date for new release planned?

In latest version [2.1 Pre-release 2] there are crashes from time to time when trying to download some large threads.
Also when starting application there are Unhandled Exception error, it can be ignored, but still.

**Comment by murrty** [comment]
I don't plan releases, but I do have a new version with updates coming out. I only really look at this program during Pokemons' leak season, so I don't really get updates out until November, when I'm active on any kind of chan, but I will push one out soon(tm).

I tried to debug issues with large threads or multiple in the queue, I can only get so many bugs without outsourced help because I just don't have the desire to go on chans anymore, given that now they're basically a cesspool of lunacy and retardation.
