### ISSUE TITLE
Crashes, high CPU usage

### ISSUE THREAD

**Issue by HoloWise** [murrty/YChanEx#6]
1. CPU usage is through the roof with app utilizing it at 40-90% constantly until it crashes.
2. App keeps throwing NullReferenceException and OutofMemeoryException after a few min of working (a few times at least) and then crashes

![image](https://user-images.githubusercontent.com/36460595/71601508-fc190700-2b53-11ea-9b20-a50e72e27859.png)

**Comment by murrty** [comment]
The last time I looked into it, I didn't understand the reason it would throw a null reference, which is why I kept #4 open. It's not very consistent and I want to redo it, as I feel like the process threading for downloads is shoddy and could be reworked into something better.

When I have time to commit myself to reworking it, I'll do it, but for now your best bet is to silence the errors in the settings, I haven't seen it miss files by doing so.

I'm also surprised u18chan still works, it parses the html of the threads to download, because they don't have AN API YET nor support last-modified in the headers.

**Comment by HoloWise** [comment]
A bit of a late answer lol. Got busy with irl stuff. I'm running it on i5 6400 so that usage is definitely not normal for the task the app performs. Also from your answer I assume OOM/Null Reference exceptions shouldn't affect the app at all so idk what's the source of crashing (altho just now I noticed that the app was running fine but I couldn't bring up the UI, not sure if that was the case in the past since I haven't used the app for a while)

A different issue tho. I just noticed that the app got 404 on some perfectly fine threads and removed them from the list of Threads.

**Comment by murrty** [comment]
I see. At the moment I'm in the process of getting another program finished, but I will be looking into this soon, hopefully with a more refined thread system and fix the threading problems with this. Hopefully.

That's interesting. I think it might be a false 404 on a bad connection that gets refused for any reason.

**Comment by murrty** [comment]
Hey, I made an [alpha build](https://github.com/murrty/YChanEx/releases/tag/2.0-alpha1) of the next release. If you still seem to have this issue, would you try it out for me and tell me if it alleviates some problems you describe?

**Comment by HoloWise** [comment]
Just downloaded it a few minutes ago and migrated 17 u18chan links from the old version

For the old version:

Download folder has ~11581 files and doesn't grow so the app is only waiting for new images (timer set to 120 seconds), no exceptions since there's nothing to download but the usage sits at ~40-60% cpu with high spikes here and there to ~90% and 500-800MB memory (occasional disk usage, no network usage)

For the new version

Download folder is at ~1,771 right now and growing since it uses the same set of links, no exceptions so far. While actively downloading from multiple threads usage seems to move from as low as 0% to as high as 70%, but it's mainly in a 5% to 30% range, when adding links it sits at 60% but I was adding multiple pages with thousands of images at once, memory usage sits in ~700-1300MB range (disk and network usage present since it's downloading)

Ok so it's been running for a while now. I actually went out to do some shopping. When I came back I noticed it threw 3 OOM exceptions, 

![image](https://user-images.githubusercontent.com/36460595/75563682-091a7f80-5a4b-11ea-90a0-e1df506c39c8.png)

Downloading stopped at ~10621 files, i looked around a bit and in at least one folder it was missing most of the thumbnails (I assume OOM forced downloading to stop) Found some other regular files missing but a lot were just removed from u18 so I didn't bother looking further into it cuz it'd take ages to check if they still exist on u18 and there's already an obvious example that it stopped downloading.

Even in that state disk and network usage randomly jumps from 0% to 0,1-0,5%, ram sits at around 400-600mb and cpu sits at 40-75% (maybe more, I didn't look at it long enough so I didn't see any spikes). Closing app didn't actually close it, it kept running and there was no icon in trey but it's an alpha build so ye lol, 

I killed the process and started it again to see what it'll do. I added all the threads again, Usage seemed to be stuck at ~50-70%, after a while of scanning folders and stuff it downloaded some of the missing files and threw some exceptions again (520 and 522 from server). Downloading stopped for a while but it's downloading again, there are still some missing files, usage remains high ~60-70%

![image](https://user-images.githubusercontent.com/36460595/75569583-abd7fb80-5a55-11ea-98e4-cd2595326dba.png)

![image](https://user-images.githubusercontent.com/36460595/75569593-b2667300-5a55-11ea-8751-18a910022730.png)

After a while it ended up stopping at  11577 files so at this point I assume that it got everything and the difference comes from the fact that some files were deleted from u18chan (also 520 522 exceptions maybe?). Usage remains between 50 and 80% with occasional spikes above that even tho in theory app doesn't do anything other than scan pages for new images.

So yeah in the end it feels the same, just less exceptions and crashes. I haven't looked into the source code yet so I can't really suggest anything but I'll read through it next week after I'm done with uni.

**Comment by murrty** [comment]
I can try to add some garbage cleaning at the end of every scan, but there still is a major issue with even using u18chan. The admins don't use [last modified](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Last-Modified) headers nor the depreciated [ETag](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag) header anywhere. This application does support it, but they don't and that will lead to issues for both users and their administrative team, such as 5XX errors, which is on their end. Unless they have an API I don't have any clue of, I can't really do much else with those errors because parsing their HTML is the best route I know of.

I can try to fix the out of memory issues, I don't know if calling garbage collection will appropriately fix it, but I can call it every scan and see what happens. I don't really know of any other reason it could be calling an out of memory exception.

If you do look into the source, look at the 2.0 branch, it's the one I'm actively working on. It's not clean, but its a work in progress.

**Comment by HoloWise** [comment]
I scrolled through the code really quick before going out for uni. I'll take a better look on Monday.

Maybe instead of entering the download process after each scan, you could check if current html file is different when compared to one from the previous scan? (store and compare md5?)

**Comment by murrty** [comment]
I'm considering leaving HTML in memory since it's probably better off there than being written to the drive every X seconds to save on write cycles if someone's on an SSD. I just wish they'd support useful headers instead of living in 1983, save us all the trouble.

**Comment by HoloWise** [comment]
lol yeah that'd make things a lot easier for sure. I got a bit busy cuz they gave us a lot of projects this semester so I'll look through your code later this week. 

Just an idea tho, maybe add an option to pick a max amount of threads that can run concurrently and add a thread queue? (so based on how the app works now you'd have to account for check timer running out when all available threads are busy) It could help with the issue I experience but I wouldn't treat it as a fix, just a feature suggestion

**Comment by murrty** [comment]
The way it's setup now is that each thread is on their own download timer, so multiple threads can be downloaded simultaneously. I was thinking about having each thread in a queue, so they download one at a time instead of separate, but then I put into account they could 404 before the downloader gets to them.

The OoM exception is program based, I read that threads properly dispose of their information at the end of the thread, but considering that the exception keeps occuring, I have to wonder if it's because the thread isn't properly doing that. Or is creating a new thread every download doing something? my head hurts.

I'm probably gonna put this project on the backburner for a while, I don't have much motivation to continue it at this time, and the current release still works, albeit with some issues.

**Comment by s16796** [comment]
Are you creating new thread for each download? Wouldn't it be better to write it so that it can reuse existing threads? (ThreadPool?) 

And ye got you, It still works so I can run it occasionally.

**Comment by HoloWise** [comment]
Wouldn't it be better write it so that it reuses threads using ThreadPool instead of creating new threads for each download?

And yeah I got you. It still works so I can just run it occasionally to update my folders.

**Comment by murrty** [comment]
Currently, it creates a new form per chan thread. I don't think a ThreadPool will be helpful if there's going to be multiple forms instead of a single one. But now I think, instead of redefining the thread every download, make it define the thread once and then just start the thread when downloading, which I think it should work.

**Comment by murrty** [comment]
No idea if it still occurs, I don't have any issues with high CPU usage.

**Comment by murrty** [comment]
u18chan has completely changed logic now, so it should be better. i am hoping that looping in a single thread improves performance, instead of re-creating it when need be.
